### ISSUE TITLE
Argument count error for #table using a list of column names

### ISSUE THREAD

**Issue by migueesc123** [microsoft/vscode-powerquery#105] opened 2021-08-13 14:43 UTC
![image](https://user-images.githubusercontent.com/9544580/129374093-d870db9a-7dc0-4770-83ec-1c424b0e0286.png)
Repro steps:
1. Create a new table where the first argument is a list of columns such as {"Column1", "Column2"} and complete the rest of the code
2. Note how the first argument of the constructor appears to be incorrect according to the editor

**Comment by ninmonkey** [comment] 2021-09-01 21:42
What is your environment? 

Were you using an **unsaved file**? Sometimes I get errors, it just might be when I create a new tab, and never save it.

If I have a saved file I get no errors

## Test Query
```ts
let
    miguel = #table(
        {"Column1"},
        { {1} }
    ),
    matt = Table.AddColumn(
        miguel,
        "New",
        each Number.Acos([Column1]),
        type any
    )
in
    matt
```
## Environment

```
PowerQuery.vscode-powerquery@0.1.21
1.60.0-insider - efaa9c304bba61bdce8b0d39db5df94ce3a53fb6 - x64
```

Generated by:
```ps1
🐒> code --list-extensions --show-versions | Select-String 'powerquery'
    (code --version) -join ' - '
```

**Comment by ninmonkey** [comment] 2021-09-01 23:16
Edit: After further testing it seems like the linter gets stuck. It seems like an event isn't firing. But if you close and reopen it, then it says it's valid. I have extensions that modify `inlay` warnings, so it's possible it's related to that.
![vscode-parse-event - 2021-09-01 -- octree - 64](https://user-images.githubusercontent.com/3892031/131757503-3a1c573e-0987-494d-8e62-7a40f315242b.gif)

I **am** able to reproduce it consistently

**Comment by JDCAce** [comment] 2021-09-02 03:34
I used to get a similar or identical error whenever the parser (linter? I don't know the terminology) attempted to use a previously defined variable which it couldn't determine the type of. To fix the issue, the variable's type must be explicitly cast, using `as` either during its declaration (see Note 1 below) or its use. Unfortunately, it brings up two more errors, both of which are type errors as well:

![image](https://user-images.githubusercontent.com/758002/131775273-330a4aa2-9ef0-40f6-b27d-62a166f15f5b.png)

- The Line 7 error is easy: `#table` creates a variable of type `any` (for some reason). Casting it to table will fix that error; again, it can be cast either in its declaration or its use.
- The Line 10 error I haven't figured out completely yet. One option that is available in this case is another explicit cast: `any as type`. However, I just noticed tonight this doesn't work for `nullable any` or any type with `nullable` in it. I just circumvent the error using `Any.Type` instead of `type any`.

Note 1: In this case, the unknown variable is a value inside a column. You can explicitly cast `1` as a number, but that doesn't fix the issue. I assume this is because the entire column needs to be cast, and as far as I'm aware that cannot be done using `as` anywhere in `#table`; instead, `Table.TransformColumnTypes()` would be needed.

**Comment by JDCAce** [comment] 2021-09-02 04:14
To state something I simply implied in my last post, this is not an error with the `#table` parsing/linting. The problem arises with the usage of that table (or values in that table). The most reliable way of determining where the error occurs is the following:

Hovering the mouse cursor over each value being assigned (i.e., those to the left of any assignment operators `=`) will reveal a normal pop-up box for every assigned variable **before** the expression containing the error. Hovering over the variable containing the error will be the first variable that does **not** produce a hover popup box. In the example above, the first assigned variable that doesn't produce the popup is `matt` because the error occurs in the right-hand side of that assignment expression. This process may be used even before any error has been reported by VS Code (i.e., when there are no red squiggles). This indicates the error is there before @ninmonkey's comma-3 trick is employed. (Coincidentally, I use the same method of putting a digit after a comma when I want to force the red squiggles to appear.)

PS – I apologize for what I assume must be confusing terminology in my posts. I largely taught myself Power Query and M, and I haven't learned all the proper terminology, so I use terms borrowed from different technologies that I know.

**Comment by ninmonkey** [comment] 2021-09-10 19:26
> Parsing / linting

That's a good point, I thought some of my tests were errors, but some were type warnings. It should split the severity like:

| Type | Severity | 
| - | - |
| `powerquery(Error.Parse)` | Error |
| `powerquery(Error.InvokeArgumentTypeMismatch)` | Warning |

Like `optional nullable` parameters should show warning, verses the error severity, like this:
![image](https://user-images.githubusercontent.com/3892031/132906809-c7ce1730-a8cf-4855-8ace-835fb21ac5ba.png)


### Type Errors

> problem arises with the usage of that table... pop up blank

At first I thought `#table()` specifically isn't detecting the return type, so coercing fixed it. (The other table constructors are working), so I added it to #86 . But TIL the specs say [\#table](https://docs.microsoft.com/en-us/powerquery-m/sharptable) returns `type any`. So that part was operating as expected. 

### terminology

parser/linter: I've been kinda loose with that terminology. There is a [PQ Parser](https://github.com/microsoft/powerquery-parser), [PQ Language Service](https://github.com/microsoft/powerquery-language-services), and this extension. 

For data types, the language itself, only has `primitive types`. That's any of these:

`any`, `binary`, `date`, `datetime`, `datetimezone`, `duration`, `function`, `list`, `logical`, `none`, `null`, `number`, `record`, `table`, `text`, `time`, `type`

Then there's `ascribed types`, like `Int64.Type` or `Decimal.Type`, which add metadata to values that functions can use. Both are `type number`. Try `Table.Schema( someTable )` and check out the columns `Kind` and `TypeName`

### How to type line 10

> Line 10 error I haven't figured out completely yet.

Here's how I'd add typing. I omitted `as table` on purpose.

```js
let
    miguel = #table(
        type table[Num = Int64.Type],
        { {13} }
    ),
    /*
    this next step is mostly redundant -- because I declared a table type (ie: schema)
    But -- TransformColumnTypes actually transforms the data, rather than ascribing the type
    It uses the the current locale (or set it as the last arg) 
    for converting text to numbers/dates/times/etc 
    */    
    miguel_typed  = Table.TransformColumnTypes(
        miguel, { {"Num", Int64.Type} }
    ),
    FinalTable = Table.AddColumn(
        miguel_typed,
        "New",        
        (row as record) as number =>
            Number.Acos( row[Num] ),
            Int64.Type
    )
in
    FinalTable
```

I never use `each` with a `Table.AddColumn`, because `each` is synatic sugar to declare a function that returns `type any`. But the column's type uses that function's return type, to set the column type. That, plus the 4th argument.

```js
each [Num] + 10
// evaluates as
(row as any) as any => row[Num] + 10
```

This last part might be hard for statically detecting types
![image](https://user-images.githubusercontent.com/3892031/132906137-bbdd6c44-d44b-4404-8cc6-c7799948eb27.png)

### Resources on Power Query

Note: `Power Query` and `M` are names for the same language. 

- The language docs have a ton of info on the sidebar: https://docs.microsoft.com/en-us/powerquery-m/m-spec-values
- This series is great https://bengribaudo.com/blog/2018/02/28/4391/power-query-m-primer-part5-paradigm
- There's a [Power BI Discord](https://discord.gg/9StERjyPEY) server

**Comment by migueesc123** [comment] 2021-10-14 10:28
gj @JordanBoltonMN ! my scenario works now :) 

I'm not entirely sure what the rest of the replies mean if i'm being honest with you, so i'm unsure if there are other hidden bugs identified by @JDCAce  or @ninmonkey, so i'll leave this issue open and let you be the judge if you wish to close it as I no longer have the issues statement in my initial post.

Thx again and keep up the good work!

**Comment by JordanBoltonMN** [comment] 2021-10-14 21:21
Glad it's working for you. I'll be closing this issue as I created a bug in another repo/layer - https://github.com/microsoft/powerquery-language-services/issues/131

**Closed by JordanBoltonMN** 2021-10-14 21:21 UTC
