### ISSUE TITLE
Only show M functions and language features relevant to what the user is doing

### ISSUE THREAD

**Issue by cwebbbi** [microsoft/vscode-powerquery#24] opened 2019-09-18 18:14 UTC
Some M functions and language features are only available or relevant in certain scenarios: for example, many M functions can only be used in custom connectors. It would be useful to provide some kind of switch that would allow a user to specify whether they were writing M for Power BI Desktop, Excel, dataflows or custom connectors etc. Setting this would stop users from seeing functions and language features that are not relevant for what they are doing.

**Comment by bgribaudo** [comment] 2020-07-13 17:58
Agreed. Maybe a 'target environment' drop down choice or configuration setting?

**Comment by JordanBoltonMN** [comment] 2021-06-27 18:39
The language services layer now operates by having a higher level (such as the VSCode extension) supply it with definitions for a standard library. The next step is create definitions for the various operating contexts that Power Query works under. It will likely be some time before this is officially supported, but work is being done on it!

**Comment by bgribaudo** [comment] 2021-06-28 12:47
Thanks for the update, @JordanBoltonMN!

**Comment by JordanBoltonMN** [comment] 2022-03-14 17:07
Closing as potential duplicate of SDK support. See #127

**Closed by JordanBoltonMN** 2022-03-14 17:07 UTC
